### PR TITLE
Fix false positive of no-outlet-outside-routes

### LINKED ISSUE #761: False positive when app's name is "components"
I just discovered there's a false positive when the app's name is _"components"_:

```
components/templates/application.hbs
  12:0  error  Unexpected {{outlet}} usage. Only use {{outlet}} within a route template.  no-outlet-outside-routes
```

This is actually the application route's template but the app happens to be named "components".

Reproduction available here: https://github.com/simplabs/ember-workshop/tree/master/examples/components

### PR DESCRIPTION
**Pull request by marcoow**
This checks the module name includes `templates/components` and thus makes sure the template is actually a component template vs. any templates where the app names happens to be _"components"_ (e.g. `components/templates/application`).

closes #761

### CODE REVIEW

File: lib/helpers/is-route-template.js [hunk 1]
```diff
@@ -19,6 +19,6 @@ module.exports = function isRouteTemplate(moduleName) {
   var isPartial = baseName.indexOf('-') === 0;
 
   return (
-    !isPartial && moduleName.indexOf('components/') === -1 // classic component
+    !isPartial && moduleName.indexOf('templates/components/') === -1 // classic component
```
Comment (bmish) [inline lib/helpers/is-route-template.js]: To be even safer, could you change it to `/templates/components/` with the leading slash?

Comment (marcoow) [reply lib/helpers/is-route-template.js]: sure, done

File: lib/helpers/is-route-template.js [hunk 2]
```diff
@@ -19,6 +19,6 @@ module.exports = function isRouteTemplate(moduleName) {
   var isPartial = baseName.indexOf('-') === 0;
 
   return (
-    !isPartial && moduleName.indexOf('components/') === -1 // classic component
+    !isPartial && moduleName.indexOf('/templates/components/') === -1 // classic component
```
Comment (rwjblue) [inline lib/helpers/is-route-template.js]: Hmm, with the upcoming changes for co-location (emberjs/rfcs#481) we won't be using `app/templates/components` any longer.

Specifically, these are both valid component template locations:

```js
app/components/foo.hbs
app/components/foo/index.hbs
```

Comment (marcoow) [reply lib/helpers/is-route-template.js]: So could we do

```es6
!isPartial && moduleName.indexOf('<appname>/templates/components/') === -1 && moduleName.indexOf('<appname>/components/') === -1
```

instead then?

Comment (efx) [reply lib/helpers/is-route-template.js]: @marcoow @rwjblue What about just checking for the `/components/` path?:
```js
!isPartial && !moduleName.includes('/components/')
```

Comment (efx) [reply lib/helpers/is-route-template.js]: Well, reading the original issue we cannot do just the `/components` string given that example route.

Comment (marcoow) [reply lib/helpers/is-route-template.js]: `<appname>` would be `app` in most tests here, yes - in reality it's the app's actual module name, e.g. `my-app`. I updated this to support co-located component templates as well.

**Comment by efx** [comment]
Also closes #700
